### ISSUE TITLE
Release of the dataset

### ISSUE THREAD

**Issue by fabienbaradel** [DmZhukov/CrossTask#1]
Hi @DmZhukov ,
Thanks for your very interesting paper and the introduction of a new dataset. I was wondering about when are you going to release the dataset?
Best,

**Comment by DmZhukov** [comment]
Hi Fabien,
Thanks for your interest in our work. We're planning to release the dataset in a couple of days
Best,
Dimitri

**Comment by fabienbaradel** [comment]
Thanks for the very fast answer, I do appreciate.
That's a good news, perfect.
Best,
Fabien
