### ISSUE TITLE
Unavailable videos in youtube

### ISSUE THREAD

**Issue by fcorencoret** [DmZhukov/CrossTask#2]
Hey! 

I was trying to download the videos of CrossTask but I the following videos aren't available in youtube any more:

`['j9TLx0PpfCg', '4TVwfRVamss', '1GLKecfTCYY', 'ukRo8KvGQAg', 'Mlscv4JxrfU', '6oZa95IPIz0', 'GpXQ85E20WA', 'o6taBNbVc2g', 'KkNhwcxkY9Y', 'O-rjESRQmH0', 'K99HueeH4UI', 'UgnXGTMGPgM', 'Jhxv3gohIA4', 'StaPQKTMatI', '8iz7U_7tE2o', 'ev5Iah2l390', 'sT9M5M6EZMQ', 'VXMO6HycHUk', 'ZTiuU_b6fh0', 'A_0-qMkfCYs', 'bp__fS2siNg', 'hQGil8MPacU', '1yqpjJGH6Yc', 'Xs6QuxZ5DK8', 'DBRp2qABm-4', 'Nxok_XFt3es', 'l5D-k3_1zU0', 'ioRsRjPx_Cs', '-TcCWq3PY70', 'DQSBnB6yr-k', 'Vzq2iz_v-z4', 'HaFsZXqBdQM', '3kIs5YyLd_M', 'lakgaU32Now', 'WUvBCrFDReI', 'XpV0hthmFo0', 'OEchkgHTKhg', 'q8mW35dSxQI', 'YOZ67AcppfA', 'Ou5RXSukI74', 'Y_sumhhfa30', '48sIo5pJ39Q', 'Iw8IAMVFJEY', 'K7XszLKoZaQ', 'AQ5N7RhBqio', 'Z8mK-j-z-uc', 'YHOoOzXYgKo', 'bbum2hlKx5Q', 'hkMNUQmK8R0', 'R2IpprucumU', '2ws1uLGBtmo', 'ZgdaPuy35Ao', 'Uxm5Y7fz-V0', 'bz1MJDH5XCY', '7v4blGJNVbU', '6TVQ-eIqiJQ', 'UbTLDyYReI4', 'u8Nd5wUkwP4', '9873pdqw0s0', 'tBgrtBpSS70', 'jLK4sTcJsX0', 'UN0zFmcrjaQ', 'en0e-ChQscI', 'sUMI9PzSskg', 'LSi-NWtcycA', 'QjjHv-XFto4', 'oDYI2Jf_F28', 'PhCyhhxLEbI', 'PwXYQ9E7YqA', '4_rW6SKFLl8', 's6w8fiQaJeI', 'PdmLpakp2yA', '7ryvdJPshvI', '-gv5WwaaWFY', 'jVSqksLfZuE', 'aMvbio_IZ0s', 'a6A9YaE7YO4', 'VKgMmtXwsno', 'EHH5yIqMOqY', '91D39GRTd0Q', 'DbuSZHZQZCQ', 'HIH6iRVQgAA', 'qjkhNf0-AIA', 'DRbzPFfXBEU', 'qoTRM6aXrlg', 'QzPE3BISgbM', 'u546n1es45k', 'theq27CMbDk', '-Yu4tm9pm38', 'WgGh9z6tUps', 'gV8zPFoE5BI', 'Y7deWVwM3ks', '1DxEhuNqG38', 'YpgjbPrzvpM', 'NMpBJvgIMDQ', 'VaHyNUHcrfM', 'lVC8mA3-yUI', 'VSWOyOyykIg', '10Uof0hFZZw', 'w0PmMtDhEYg', 'LLKNdpfEy0M', 'IfNmmbYpylY']`

Is there any way you could provide those videos please? On the other hand, the paper mentions there are 4713 videos (2763 primary + 1950 related), but your videos.csv only provides 4700 videos. Could you provide those as well?

Thanks!

**Comment by DmZhukov** [comment]
Hi @fcorencoret 
There's only 2750 videos for primary tasks indeed. 13 remaining videos are not a part of the dataset and they were not used in our experiments. We're preparing a new arxiv version with fixed statistics.
As for the videos that are no more available, please contact me by mail dmitry.zhukov@inria.fr and I'll provide them

**Comment by YunseokJANG** [comment]
Dear @fcorencoret ,

Hi, my name is Yunseok Jang, a Ph.D. student at the University of Michigan, Ann Arbor. I recently tried to obtain all the CrossTask videos by reaching out to Dimitri, but we failed to obtain 4 videos from the training set at the end; which are listed at the end of this message. However, I realized that you did _not_ mark them as missing, so I guess you _may_ have a chance to have those if you didn't remove the original videos. If you (or someone who will read this message later) have those videos, then would you mind if I ask you to share those with Dimitri? Hope to hear great news from you.

Regards,
Yunseok Jang

------- missing_videos.csv -------
task_id, video_id
44043, vLGYwrlhZGk
114508, 8ti7rJ882Hk
14133, QlK6Mrujf-o
93400, SHGhzeYqHKc

**Comment by fcorencoret** [comment]
Videos are no longer available where I got them from 😞

**Comment by YunseokJANG** [comment]
Oh, I see. Thanks for your quick follow-ups, @fcorencoret . I hope someone who downloads the dataset earlier can share those with Dimitri sometime soon 🤞
