### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Petr-Byv** [DmZhukov/CrossTask#3]
Great work. Probably a typo - update 30 of April not May. One question, in the paper you mention that during the testing only and ordered list of steps is given. Does that mean that for a video which covers an incomplete list of steps (let's say 7 out of 8 steps of the task) the model is still forced to output all 8 fixed steps, even though one step is missing in the test video.

**Comment by DmZhukov** [comment]
Thanks, it's fixed.
Yes, it is always forced to predict all steps and in the same order.
The model is quite easy to modify for the "video-level" weak supervision (steps present in the videos in the video-specific order), that is a common approach nowadays. Here we tried to explore a weaker "task-level" supervision, which is easier to get
