### ISSUE TITLE
Viewing the frames

### ISSUE THREAD

**Issue by Sidcvs** [DmZhukov/CrossTask#4]
Is it possible to extract the frames to view the output ? 
When I convert it to numpy it becomes an empty image

**Comment by DmZhukov** [comment]
Can you specify what output do you mean? If it's assignment Y, it should normally contain k units, where k is the number of steps.
What do you mean by "extract the frames to view the output"?

**Comment by coderoda** [comment]
I would like to view the frames of the video along with the corresponding
tasks.

**Comment by coderoda** [comment]
Is there any way
