### ISSUE TITLE
code for feature extraction and dataset request 

### ISSUE THREAD

**Issue by Zoe0123** [DmZhukov/CrossTask#8]
Hi, thank you for the excellent work! We have same with the problems in last thread that some video links are expired. Could you please share the downloaded videos? 
and we are also curious about how did you get the 3200-dim features for the videos. Could you also kindly share the code for the feature extraction, if possible?

**Comment by DmZhukov** [comment]
Hi,
You can download most of missing videos using these temporary links
https://www.rocq.inria.fr/cluster-willow/dzhukov/missing_videos.tar.gz
https://www.rocq.inria.fr/cluster-willow/dzhukov/missing_videos_2.tar.gz
https://www.rocq.inria.fr/cluster-willow/dzhukov/missing_videos_3.tar.gz
https://www.rocq.inria.fr/cluster-willow/dzhukov/missing_videos_4.tar.gz
I'll try to provide a link to all missing videos in readme soon

**Comment by Zoe0123** [comment]
Thank you!!! And could I also have the code for feature extraction, if possible?

**Comment by DmZhukov** [comment]
Yes, I'm preparing the code for release

**Comment by Zoe0123** [comment]
Thanks!!
