### ISSUE TITLE
Some missing videos might be corrupted

### ISSUE THREAD

**Issue by xiangyh9988** [DmZhukov/CrossTask#9]
Hi, after I downloaded and unpack `missing_videos.tar.gz`, I found some videos were too small in size, e.g., 512K ~ 2.0M. Then I try to play them on my PC, only the first few seconds can be played then they got stuck. When I process them using `ffmpeg-python`, the `shape[0]` of the final numpy array is less than the duration of the corresponding annotation file, e.g., ` Gy3MURE_2Jw.mp4`.

Here are some video files with small size. Are these videos corrupted? I have downloaded and unpack the tar file twice to ensure I download it correctly.
<img width="245" alt="crosstask_wrong_videos" src="https://user-images.githubusercontent.com/24634140/168010356-4ce395c1-3804-4ffa-966f-78058e605d6c.png">

**Comment by DmZhukov** [comment]
Yes, a few files are corrupted, you will have to remove them

**Comment by xiangyh9988** [comment]
Thanks for your reply!
